logging:
  level:
    org:
      springframework:
        security: DEBUG

server:
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  security:
    oauth2:
      client:
        registration:
          github:
            scope: user:email, read:user
            redirectUri: ${GH_REDIRECT_URI}
            clientId: ${GH_CLIENT_ID}
            clientSecret: ${GH_CLIENT_SECRET}

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

google:
  secret:
    key: ${GOOGLE_SECRET_KEY}
    cx: ${GOOGLE_CX}

lambda:
  secret:
    url1: ${LAMBDA_SECRET_URL1}
    url2: ${LAMBDA_SECRET_URL2}

cloud:
  aws:
    credentials:
      accessKey: ${S3_ACCESS_KEY}
      secretKey: ${S3_SECRET_KEY}
    s3:
      bucket: ${S3_BUCKET}
    region:
      static: ap-northeast-2

bucket:
  dirname: ${S3_DIR_NAME}